[server]
# Production server configuration
port = 8501
address = "0.0.0.0"
headless = true
runOnSave = false
enableCORS = true
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
# Optional: customize the theme
# primaryColor = "#FF6B35"
# backgroundColor = "#FFFFFF"
# secondaryBackgroundColor = "#F0F2F6"
# textColor = "#262730"
