# Streamlit secrets configuration
# This file prevents StreamlitSecretNotFoundError

[general]
DEBUG_MODE = false

# Database configuration (can be overridden by environment variables)
# DATABASE_URL = "postgresql://user:password@host:port/database"
